name: Cache‑Clean
on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu‑latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete cache
        uses: actions/github‑script@v7
        with:
          script: |
            const caches = await github.rest.actions.listRepositoriesCaches({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            for(const item of caches.data.actions_caches){
              await github.rest.actions.deleteRepositoryCache({
                owner:context.repo.owner,
                repo:context.repo.repo,
                cache_id:item.id
              })
            }
